import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import { Toaster } from 'sonner';

const poppins = Poppins({ 
  subsets: ["latin"],
  weight: ['400', '500', '600', '700'] 
});

export const metadata = {
  title: "Oficina do Dev",
  description: "Generated by Oficina do Dev",
};
const AuroraBackground = ({ children }) => {
  return (
    <div className="relative flex flex-col h-screen items-center justify-center bg-slate-900 transition-colors">
      <div className="fixed inset-0 overflow-hidden">
        <div className="absolute -inset-[10px] opacity-50">
          {/* Esferas de luz animadas */}
          <div className="absolute top-[-10%] left-[-10%] w-[70%] h-[70%] rounded-full bg-gray-500 blur-[120px] animate-pulse" />
          <div className="absolute bottom-[-10%] right-[-10%] w-[60%] h-[60%] rounded-full bg-blue-500/30 blur-[120px] animate-bounce [animation-duration:10s]" />
          <div className="absolute top-[20%] right-[10%] w-[50%] h-[50%] rounded-full bg-purple-500/20 blur-[120px] animate-pulse [animation-duration:8s]" />
        </div>
      </div>
      <div className="relative z-10 w-full h-full overflow-auto">
        {children}
      </div>
    </div>
  );
};
export default function RootLayout({ children }) {
  return (
  <AuroraBackground>
    <html lang="pt-br" suppressHydrationWarning>
      <body suppressHydrationWarning
        className={poppins.className}
      >
        {children}
        <Toaster richColors position="top-right" />
      </body>
    </html>
  </AuroraBackground>
  );
}
